// job("First-Maven-Project-Via-DSL"){
//     description("First Maven Job generated by DSL on ${new Date()} , this project is small maven")
//     scm{
//         git("https://github.com/kashivirus/anshulc55.git" , 'master')
//     }
//     triggers{
//         scm("* * * * *")
//     }
//     steps{
//         maven('clean package' , 'maven-samples/single-module/pom.xml')
//     }
//     publishers{
//         //archieve the war file generated

//         archieveAritifacts '**/*.jar'
//     }
// }



job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/kashivirus/anshulc55.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
